name: Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        # docker pull ghcr.io/betats/docker-vnc-xfce4:latest
        docker build . --tag ghcr.io/betats/docker-vnc-xfce4:$GITHUB_SHA --cache-from ghcr.io/betats/docker-vnc-xfce4:latest
        docker push ghcr.io/betats/docker-vnc-xfce4:$GITHUB_SHA
